### ISSUE TITLE
Integrate AuthService ROCK in CKF 1.7

### ISSUE THREAD

**Issue by kimwnasptd** [canonical/oidc-gatekeeper-operator#124]
### What needs to get done

Once https://github.com/canonical/oidc-authservice-rock/issues/7 is merged, we'll need to integrate it into our Charm

### Why it needs to get done

In order for us to have our own built OCI Image for that component

**Comment by NohaIhab** [comment]
closed by #125 and promoted to `ckf-1.7/stable`
