### ISSUE TITLE
If `public-url` is undefined, charm "works" (green/pod alive) but doesn't do anything useful

### ISSUE THREAD

**Issue by ca-scribner** [canonical/oidc-gatekeeper-operator#18]
If deployed and related to the appropriate charms but not set with a `public-url`, OIDC-gatekeeper will show:
* Active in juju
* pod running
* pod logs show repeated messages of `time="2022-02-11T18:18:01Z" level=error msg="OIDC provider setup failed, retrying in 10 seconds: Get /dex/.well-known/openid-configuration: unsupported protocol scheme \"\""`
This will also result in a blank screen if trying to browse to the ingress IP because the dex+oidc handling of the login is broken.  No useful messages are provided to the user to identify what is wrong.

I think at minimum we need better messaging about this to nudge users in the right direction.  But I also think (?  haven't thought it through deeply) the oidc-gatekeeper charm shouldn't be live at all if it has no `public-url`.  With `public-url=""` it just tries to do the auth flow with a non-sensical IP address.  A deeper look into this might show we're doing it right but it seems worth a look.  Either way, for our purposes I don't think `juju status` should show green if this is the case as no users can log in

**Comment by ca-scribner** [comment]
As pointed out by @grobbie, rather than setting `public-url` directly should we get the info we need from a relation with dex-auth?

**Comment by orfeas-k** [comment]
Closed by #108
