### ISSUE TITLE
`juju config oidc-gatekeeper client-secret` returns an empty string

### ISSUE THREAD

**Issue by grobbie** [canonical/oidc-gatekeeper-operator#20]
It should not return an empty string - rather it should return the `client-secret` value.

**Comment by ca-scribner** [comment]
Reasons behind this are discussed in canonical/minio-operator#35.  Whatever action is taken there can be taken here as well

**Comment by ca-scribner** [comment]
Closing as this will not be implemented.  If you need to reuse the password outside of the charm, for now the recommendation is to set the password yourself via config (`juju config charmname client-secret=xxx`) and then you can use it however you like (including pull it back out again with `juju config`)
